# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Collabora Online Development Edition systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ collabora_online_identifier }}.service"
  register: collabora_online_service_stat

- name: Uninstall Collabora Online Development Edition systemd services and files
  when: collabora_online_service_stat.stat.exists | bool
  block:
    - name: Ensure Collabora Online Development Edition systemd service is stopped
      ansible.builtin.service:
        name: "{{ collabora_online_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Collabora Online Development Edition systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ collabora_online_identifier }}.service"
        state: absent

    - name: Ensure Collabora Online Development Edition container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ collabora_online_container_network }}"
        state: absent

    - name: Ensure Collabora Online Development Edition container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ collabora_online_container_network }}
      register: network_deletion_result
      changed_when: collabora_online_container_network in network_deletion_result.stdout

    - name: Ensure Collabora Online Development Edition path does not exist
      ansible.builtin.file:
        path: "{{ collabora_online_base_path }}"
        state: absent
